name: CI Shift-Left Pipeline (Minimal)

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build Maven project
        run: mvn clean compile

      # lancer Spring Boot
      - name: Start Spring Boot app
        run: mvn spring-boot:run &

      # attendre que le serveur démarre (FIXED)
      - name: Wait for API startup
        run: |
          echo "Waiting for API..."

          for i in {1..30}; do
            if curl -s http://localhost:8080/actuator/health | grep '"status":"UP"' > /dev/null; then
              echo "API is UP!"
              exit 0
            fi

            echo "Not ready yet... attempt $i"
            sleep 2
          done

          echo "API failed to start"
          exit 1

      # lancer tests
      - name: Run tests (JUnit + Karate)
        run: mvn test
